import { Toaster } from "sonner";
import "./globals.css";
import Footer from "./_components/footer";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body>{children}</body>
      <Toaster />

      <Footer />
    </html>
  );
}
